In [20]:
import pandas
import numpy

In [2]:
filename = 'random_forest_3_state_space_search_max_features.csv'

In [3]:
df = pandas.read_csv(filename, index_col=0)

In [4]:
df

,estimators,max_features,max_depth,min_samples_split,min_samples_leaf,max_leaf_nodes,fold,accuracy_in_sample,accuracy_out_of_sample,oob_score,auc,public_score,private_score
0,100.0,2.0,NaN,2.0,1.0,NaN,0,0.999954,0.948454,0.944538,1.0,NaN,NaN
1,100.0,2.0,NaN,2.0,1.0,NaN,1,0.999942,0.938144,0.945093,1.0,NaN,NaN
2,100.0,2.0,NaN,2.0,1.0,NaN,2,0.999942,0.926690,0.945348,1.0,NaN,NaN
3,100.0,2.0,NaN,2.0,1.0,NaN,3,0.999931,0.943872,0.945209,1.0,NaN,NaN
4,100.0,2.0,NaN,2.0,1.0,NaN,4,0.999965,0.950745,0.944885,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,100.0,5.0,NaN,2.0,1.0,NaN,98,0.999942,0.941514,0.947050,1.0,NaN,NaN
999,100.0,5.0,NaN,2.0,1.0,NaN,99,0.999942,0.941514,0.946795,1.0,NaN,NaN
1000,100.0,6.0,NaN,2.0,1.0,NaN,0,0.999942,0.954181,0.947072,1.0,NaN,NaN
1001,100.0,6.0,NaN,2.0,1.0,NaN,1,0.999965,0.943872,0.946876,1.0,NaN,NaN
1002,100.0,6.0,NaN,2.0,1.0,NaN,2,0.999954,0.928981,0.947223,1.0,NaN,NaN

In [28]:
df_select = df

In [29]:
n_estimators = 100
max_features = 2
max_depth = None
min_samples_split = 2
min_samples_leaf = 1
max_leaf_nodes = None

In [30]:
df_select = df_select[df_select['estimators'] == n_estimators]

In [31]:
df_select

,estimators,max_features,max_depth,min_samples_split,min_samples_leaf,max_leaf_nodes,fold,accuracy_in_sample,accuracy_out_of_sample,oob_score,auc,public_score,private_score
0,100.0,2.0,NaN,2.0,1.0,NaN,0,0.999954,0.948454,0.944538,1.0,NaN,NaN
1,100.0,2.0,NaN,2.0,1.0,NaN,1,0.999942,0.938144,0.945093,1.0,NaN,NaN
2,100.0,2.0,NaN,2.0,1.0,NaN,2,0.999942,0.926690,0.945348,1.0,NaN,NaN
3,100.0,2.0,NaN,2.0,1.0,NaN,3,0.999931,0.943872,0.945209,1.0,NaN,NaN
4,100.0,2.0,NaN,2.0,1.0,NaN,4,0.999965,0.950745,0.944885,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,100.0,5.0,NaN,2.0,1.0,NaN,98,0.999942,0.941514,0.947050,1.0,NaN,NaN
999,100.0,5.0,NaN,2.0,1.0,NaN,99,0.999942,0.941514,0.946795,1.0,NaN,NaN
1000,100.0,6.0,NaN,2.0,1.0,NaN,0,0.999942,0.954181,0.947072,1.0,NaN,NaN
1001,100.0,6.0,NaN,2.0,1.0,NaN,1,0.999965,0.943872,0.946876,1.0,NaN,NaN
1002,100.0,6.0,NaN,2.0,1.0,NaN,2,0.999954,0.928981,0.947223,1.0,NaN,NaN

In [32]:
df_select = df_select[df_select['max_features'] == float(max_features)] if max_features is not None else df_select[df_select['max_features'].isna()]

In [33]:
df_select

,estimators,max_features,max_depth,min_samples_split,min_samples_leaf,max_leaf_nodes,fold,accuracy_in_sample,accuracy_out_of_sample,oob_score,auc,public_score,private_score
0,100.0,2.0,NaN,2.0,1.0,NaN,0,0.999954,0.948454,0.944538,1.0,NaN,NaN
1,100.0,2.0,NaN,2.0,1.0,NaN,1,0.999942,0.938144,0.945093,1.0,NaN,NaN
2,100.0,2.0,NaN,2.0,1.0,NaN,2,0.999942,0.926690,0.945348,1.0,NaN,NaN
3,100.0,2.0,NaN,2.0,1.0,NaN,3,0.999931,0.943872,0.945209,1.0,NaN,NaN
4,100.0,2.0,NaN,2.0,1.0,NaN,4,0.999965,0.950745,0.944885,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,100.0,2.0,NaN,2.0,1.0,NaN,95,0.999954,0.944954,0.944781,1.0,NaN,NaN
696,100.0,2.0,NaN,2.0,1.0,NaN,96,0.999931,0.951835,0.944990,1.0,NaN,NaN
697,100.0,2.0,NaN,2.0,1.0,NaN,97,0.999965,0.947248,0.944851,1.0,NaN,NaN
698,100.0,2.0,NaN,2.0,1.0,NaN,98,0.999907,0.941514,0.944943,1.0,NaN,NaN
699,100.0,2.0,NaN,2.0,1.0,NaN,99,0.999942,0.939220,0.944909,1.0,NaN,NaN

In [34]:
df_select = df_select[df_select['max_depth'] == float(max_depth)] if max_depth is not None else df_select[df_select['max_depth'].isna()]

In [35]:
df_select

,estimators,max_features,max_depth,min_samples_split,min_samples_leaf,max_leaf_nodes,fold,accuracy_in_sample,accuracy_out_of_sample,oob_score,auc,public_score,private_score
0,100.0,2.0,NaN,2.0,1.0,NaN,0,0.999954,0.948454,0.944538,1.0,NaN,NaN
1,100.0,2.0,NaN,2.0,1.0,NaN,1,0.999942,0.938144,0.945093,1.0,NaN,NaN
2,100.0,2.0,NaN,2.0,1.0,NaN,2,0.999942,0.926690,0.945348,1.0,NaN,NaN
3,100.0,2.0,NaN,2.0,1.0,NaN,3,0.999931,0.943872,0.945209,1.0,NaN,NaN
4,100.0,2.0,NaN,2.0,1.0,NaN,4,0.999965,0.950745,0.944885,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,100.0,2.0,NaN,2.0,1.0,NaN,95,0.999954,0.944954,0.944781,1.0,NaN,NaN
696,100.0,2.0,NaN,2.0,1.0,NaN,96,0.999931,0.951835,0.944990,1.0,NaN,NaN
697,100.0,2.0,NaN,2.0,1.0,NaN,97,0.999965,0.947248,0.944851,1.0,NaN,NaN
698,100.0,2.0,NaN,2.0,1.0,NaN,98,0.999907,0.941514,0.944943,1.0,NaN,NaN
699,100.0,2.0,NaN,2.0,1.0,NaN,99,0.999942,0.939220,0.944909,1.0,NaN,NaN